import 'package:cloud_firestore/cloud_firestore.dart';
import '../models/transaction_model.dart';

class FirestoreService {
  final FirebaseFirestore _db = FirebaseFirestore.instance;

  FirestoreService() {
    // Ensure persistence is enabled (default on mobile, but good practice to be aware)
    _db.settings = const Settings(
      persistenceEnabled: true,
      cacheSizeBytes: Settings.CACHE_SIZE_UNLIMITED,
    );
  }

  // Collection Reference: users -> {userId} -> transactions
  CollectionReference<Map<String, dynamic>> _getTransactionsRef(String userId) {
    return _db.collection('users').doc(userId).collection('transactions');
  }

  // Collection Reference: users -> {userId} -> deleted_transactions (optional archive)
  CollectionReference<Map<String, dynamic>> _getDeletedTransactionsRef(
    String userId,
  ) {
    return _db
        .collection('users')
        .doc(userId)
        .collection('deleted_transactions');
  }

  // STREAM: Get Realtime Transactions
  Stream<List<TransactionModel>> getTransactionsStream(String userId) {
    return _getTransactionsRef(userId)
        .orderBy('date', descending: true)
        .orderBy('createdAt', descending: true)
        .snapshots()
        .map((snapshot) {
          return snapshot.docs.map((doc) {
            return TransactionModel.fromMap(doc.data(), doc.id);
          }).toList();
        });
  }

  // STREAM: Get Deleted Transactions
  Stream<List<TransactionModel>> getDeletedTransactionsStream(String userId) {
    return _getDeletedTransactionsRef(
      userId,
    ).orderBy('date', descending: true).snapshots().map((snapshot) {
      return snapshot.docs.map((doc) {
        return TransactionModel.fromMap(doc.data(), doc.id);
      }).toList();
    });
  }

  // ADD
  Future<void> addTransaction(String userId, TransactionModel txn) async {
    // Use set instead of add to preserve the ID generated by the client/local DB
    if (txn.id != null && txn.id!.isNotEmpty) {
      await _getTransactionsRef(userId).doc(txn.id).set(txn.toMap());
    } else {
      // Fallback if no ID exists (shouldn't happen with proper logic)
      await _getTransactionsRef(userId).add(txn.toMap());
    }
  }

  // UPDATE
  Future<void> updateTransaction(String userId, TransactionModel txn) async {
    if (txn.id == null) return;
    await _getTransactionsRef(userId).doc(txn.id).update(txn.toMap());
  }

  // DELETE (Move to deleted_transactions optional, or just delete)
  Future<void> deleteTransaction(
    String userId,
    String txnId,
    TransactionModel txn,
  ) async {
    if (txnId.isEmpty) return;

    // Optional: Archive before delete
    await _getDeletedTransactionsRef(userId).doc(txnId).set(txn.toMap());

    // Delete
    await _getTransactionsRef(userId).doc(txnId).delete();
  }

  // RESTORE (Move back from deleted to active)
  Future<void> restoreTransaction(
    String userId,
    String txnId,
    TransactionModel txn,
  ) async {
    if (txnId.isEmpty) return;

    // Add back to active
    await _getTransactionsRef(userId).doc(txnId).set(txn.toMap());

    // Remove from archive
    await _getDeletedTransactionsRef(userId).doc(txnId).delete();
  }

  // FETCH ALL (One-time fetch for restoration)
  Future<List<TransactionModel>> fetchAllTransactions(String userId) async {
    final snapshot = await _getTransactionsRef(userId).get();
    return snapshot.docs
        .map((doc) => TransactionModel.fromMap(doc.data(), doc.id))
        .toList();
  }
}
