// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtnfZXlhAf5dllvu9WvaAG6bIA_qvmyVI',
    appId: '1:781324552554:web:6fec04912deef5f453fd13',
    messagingSenderId: '781324552554',
    projectId: 'ledger-appp',
    authDomain: 'ledger-appp.firebaseapp.com',
    storageBucket: 'ledger-appp.firebasestorage.app',
    measurementId: 'G-TQZ67SND1T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAckE6XbBKdrjy0Oep1qCSqXLyHrABnTpw',
    appId: '1:781324552554:android:d81306eacfe869c253fd13',
    messagingSenderId: '781324552554',
    projectId: 'ledger-appp',
    storageBucket: 'ledger-appp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuvshBiR56jyTV_Xo4QBvJc98EdIEny-8',
    appId: '1:781324552554:ios:b9ffcc6abac5765d53fd13',
    messagingSenderId: '781324552554',
    projectId: 'ledger-appp',
    storageBucket: 'ledger-appp.firebasestorage.app',
    iosBundleId: 'com.example.ledger',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuvshBiR56jyTV_Xo4QBvJc98EdIEny-8',
    appId: '1:781324552554:ios:b9ffcc6abac5765d53fd13',
    messagingSenderId: '781324552554',
    projectId: 'ledger-appp',
    storageBucket: 'ledger-appp.firebasestorage.app',
    iosBundleId: 'com.example.ledger',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtnfZXlhAf5dllvu9WvaAG6bIA_qvmyVI',
    appId: '1:781324552554:web:b951b50690b906c253fd13',
    messagingSenderId: '781324552554',
    projectId: 'ledger-appp',
    authDomain: 'ledger-appp.firebaseapp.com',
    storageBucket: 'ledger-appp.firebasestorage.app',
    measurementId: 'G-5MQ8T14JWH',
  );
}
